name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
## added to change the folder for the action
    defaults:
      run:
        working-directory: Rust
## end


    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
#    - name: Run tests
#      run: cargo test --verbose
